
export const CONFIG = {
  GENERATION_SIZE: 20,
  GENERATIONS: 20,
  GROWTH_FUNCTION_FRACTION: 0.6,
  MAX_DEPTH: 4,
  REPRODUCTION: {
    TOURNAMENT_SIZE: 4
  },
  NODES: {
    SCALAR: {
      MAX: 10
    }
  }
}